File system search speed up
kiwix/kiwix-xulrunner pull request #379
Opened 2016-12-02 21:46 UTC by borisfba

#371
Scanning file system with MediaStore in parallel with custom scanner.
Custom scanner shows file in the list right after it was found (You don't have to wait until full search completes)

2016-12-02 23:05 UTC, mhutti1 requested changes
Incredible work.
There are however a few issues that need to be fixed.
In addition can you make sure that we refresh the fragment in onResume()

2016-12-02 23:05 UTC, mhutti1 commented on android/src/org/kiwix/kiwixmobile/ZimFileSelectFragment.java
> +    for (LibraryNetworkEntity.Book book : books)
For uniformity can you please not uses abbreviated syntax.

2016-12-02 23:05 UTC, mhutti1 commented on android/src/org/kiwix/kiwixmobile/utils/files/FileSearch.java
> +        onFileFound(query.getString(0));
Mediascanner can sometimes return phantom files as it doesn't update instantly. We should check the file really exists before adding it.

2016-12-02 23:05 UTC, mhutti1 commented on android/src/org/kiwix/kiwixmobile/ZimFileSelectFragment.java
> -      bookDao.saveBooks(mFiles);
This here serves to refresh the database when files are deleted. If the database is not refreshed then the deleted files don't show as downloadable in the LibraryAdapter.java adapter for our library fragment. You need to re implement this somehow. (Note simply calling BookDao.getBooks() should be enough to check if all the files exist and remove where necessary).

2016-12-03 19:24 UTC, borisfba commented on android/src/org/kiwix/kiwixmobile/ZimFileSelectFragment.java
> -      bookDao.saveBooks(mFiles);
Database is now refreshed [here](https://github.com/kiwix/kiwix/pull/379/commits/77d2974bfcbced3dec55788fe02b62b13a25942f#diff-fa7f4e78c060f2453efcc57f82636b7dR228)

2016-12-03 19:29 UTC, borisfba commented on android/src/org/kiwix/kiwixmobile/ZimFileSelectFragment.java
> +    for (LibraryNetworkEntity.Book book : books)
You mean 'mRescanAdapter' and 'mFiles'?

2016-12-03 19:37 UTC, mhutti1 commented on android/src/org/kiwix/kiwixmobile/ZimFileSelectFragment.java
> +    for (LibraryNetworkEntity.Book book : books)
No I mean missing { its not essential but it makes the code a bit more readable.

2016-12-04 11:25 UTC, mhutti1 requested changes
Its almost there now. Just one small change and I think that we should be able to merge.

2016-12-04 11:25 UTC, mhutti1 commented on android/src/org/kiwix/kiwixmobile/ZimFileSelectFragment.java
We should call mFiles.clear() here, otherwise it may take some time for the list to update if a file is deleted.

2016-12-04 19:20 UTC, mhutti1 approved these changes

2016-12-04 19:20 UTC, mhutti1 commented
Looks good to me.

2016-12-04 19:20 UTC, merged